### PR TITLE
Upgrade `k8s.io/*` to `v0.28`, `sigs.k8s.io/controller-runtime` to `v0.16`

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/kind enhancement

**What this PR does / why we need it**:
Upgrade `k8s.io/*` to `v0.28`, `sigs.k8s.io/controller-runtime` to `v0.16`.

The most notable `sigs.k8s.io/controller-runtime` changes are described in:
- sigs.k8s.io/controller-runtime@v0.16: https://github.com/gardener/gardener/issues/8382
- sigs.k8s.io/controller-runtime@v0.15: https://github.com/gardener/gardener/issues/7991
- sigs.k8s.io/controller-runtime@v0.14: https://github.com/gardener/gardener/issues/7230
- sigs.k8s.io/controller-runtime@v0.13: https://github.com/gardener/gardener/issues/6661
- sigs.k8s.io/controller-runtime@v0.12: https://github.com/gardener/gardener/issues/5990

**Which issue(s) this PR fixes**:
Part of #5

**Special notes for your reviewer**:
- It is recommended to review the PR commit by commit.
- I decided to drop the units tests for `AddToManager` funcs: https://github.com/gardener/gardener-custom-metrics/blob/24edc50c613721cce643c6f8a55913da54874198/pkg/input/controller/controller_test.go#L38 and https://github.com/gardener/gardener-custom-metrics/blob/24edc50c613721cce643c6f8a55913da54874198/pkg/input/input_data_service_test.go#L74. The reason is that with the new version of the `sigs.k8s.io/controller-runtime` dependency we need to do the following change:
   ```diff
   -	if err := controller.Watch(&source.Kind{Type: args.ControlledObjectType}, &handler.EnqueueRequestForObject{}, args.Predicates...); err != nil {
   +	if err := controller.Watch(source.Kind(mgr.GetCache(), args.ControlledObjectType), &handler.EnqueueRequestForObject{}, args.Predicates...); err != nil {
   ```
   The `mgr.GetCache()` is not used when setting up the watch and this requires to add a fake cache implementation to the fake manager we have. We don't unit test `AddToManager` funcs in gardener/gardener (or in any other repo). This should be rather covered with e2e tests.
- [x] This PR depends on vendor/ dir removal: https://github.com/gardener/gardener-custom-metrics/pull/13

**Release note**:

```other developer
The following dependencies are updated:
- `k8s.io/*` : `v0.23.17` -> `v0.28.3`
- `sigs.k8s.io/controller-runtime`: `v0.11.2` -> `v0.16.5`
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
/hold
I have to do adaptations after https://github.com/gardener/gardener-custom-metrics/pull/23

**Comment by ialidzhikov** [comment]
I pushed the adaptations but it is still being [processed](https://github.blog/changelog/2023-09-26-more-details-provided-when-a-pull-request-is-merged-indirectly-or-is-still-processing-updates/#pushed-commits-are-still-being-processed) by GitHub. Look like there is a GitHub [outage](https://www.githubstatus.com/) going on.

**Review by plkokanov — APPROVED** [review]
/lgtm

**Pull request merged**
